apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskmanager-deployment
  labels:
    app: taskmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskmanager
  template:
    metadata:
      labels:
        app: taskmanager
    spec:
      containers:
        - name: taskmanager
          image: tejalb29/task-manager:v1.0
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: taskmanager-config